# 该文件添加到了.ignore文件中，所以不会被上传到github上

server:
  port: 9000

spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/project?serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/course-system?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Xie20021008
